---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: kratix-platform-system
type: Opaque
stringData:
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
---
apiVersion: platform.kratix.io/v1alpha1
kind: BucketStateStore
metadata:
  name: default
spec:
  endpoint: minio.minio-system.svc.cluster.local:9000
  insecure: true
  bucketName: kratix
  secretRef:
    name: minio-credentials
    namespace: kratix-platform-system
---
apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
  name: platform-cluster
  labels:
    environment: platform
spec:
  stateStoreRef:
    name: default
    kind: BucketStateStore
  path: platform-cluster
